[tools]
"github:uutils/coreutils" = "0.10.0"

eza = "latest"
bat = "latest"
ripgrep = "latest"
fd = "latest"
zoxide = "latest"
bottom = "latest"
dust = "latest"
yazi = "latest"
fzf = "latest"
neovim = "latest"
uv = "latest"
ruff = "latest"
bun = "latest"

"github:YS-L/csvlens" = "latest"
